# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import msgs.models
import msgs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=240, validators=[msgs.validators.URLsNotAllowed])),
                ('favorite', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=models.SET(msgs.models.set_deleted_user), related_name='msgs_msg_sender_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='msgs_msg_user_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
